title: Manoj Kumar Vallabhaneni
logo: linked.jpg  # Replace with actual file path if in a subfolder
description: >-
  Aspiring Data Analyst | Data Engineer | Data Scientist — Passionate about transforming data into insights 🚀
theme: jekyll-theme-minimal

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      css: "assets/css/custom.css"


